# Generated by Django 6.0.5 on 2026-06-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'Conservação',
                'verbose_name_plural': 'Conservações',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='descricao')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='estoque.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descricao do Produto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Produto')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras / RFID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação do Estilo')),
                ('cor_principal', models.CharField(max_length=50, verbose_name='Cor Principal')),
                ('tamanho_etiqueta', models.CharField(max_length=10, verbose_name='Tamanho de Etiqueta')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('U', 'Unissex'), ('I', 'Infantil')], max_length=1, verbose_name='Gênero')),
                ('marca_estilista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca ou Estilista')),
                ('total_locacoes', models.PositiveIntegerField(default=0, verbose_name='Número de Locações Realizadas')),
                ('preco_aluguel_padrao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Aluguel')),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo de Compra')),
                ('multa_atraso_diaria', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor cobrado por cada dia de atraso na devolução', max_digits=10, verbose_name='Multa por Dia de Atraso')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.categoria', verbose_name='Categoria')),
                ('conservacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.conservacao', verbose_name='Conservação')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
    ]
