# Generated by Django 6.0.5 on 2026-06-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, unique=True, verbose_name='Nome da Cor')),
                ('codigo_hex', models.CharField(blank=True, help_text='Código hexadecimal da cor com # (Ex: #000080 para Azul Marinho). Isso permite exibir a cor real na tela do sistema ou site.', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='cor_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.cor', verbose_name='Cor Principal'),
        ),
    ]
