# Generated by Django 6.0.5 on 2026-06-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_cor_alter_produto_cor_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('descricao', 'categoria_pai')},
        ),
    ]
