# Generated by Django 6.0.5 on 2026-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservacao',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição do Produto'),
        ),
        migrations.AlterField(
            model_name='status',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
    ]
