# Generated by Django 6.0.5 on 2026-06-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_conservacao_descricao_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
