# Generated by Django 6.0.5 on 2026-06-15 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_conservacao_ativo_cor_ativo_produto_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tecido')),
                ('composicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Composição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tecido',
                'verbose_name_plural': 'Tecidos',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='tecido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.tecido', verbose_name='Tecido Predominante'),
        ),
    ]
