# Generated by Django 6.0.5 on 2026-09-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_tecido_produto_tecido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecido',
            name='composicao',
        ),
    ]
