# Generated by Django 6.0.5 on 2026-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_remove_tecido_composicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('IMP', 'Importado')], default=1, max_length=3, verbose_name='Origem do Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('NVA', 'Noiva'), ('NVO', 'Noivo'), ('DEB', 'Debutante'), ('PAD', 'Padrinho'), ('MAD', 'Madrinha'), ('DAM', 'Daminha'), ('FES', 'Festa'), ('COM', 'Comum')], default=1, max_length=3, verbose_name='Tipo do Produto'),
            preserve_default=False,
        ),
    ]
