# Generated by Django 6.0.5 on 2026-10-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_produto_origem_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('I', 'Infantil'), ('M', 'Masculino'), ('U', 'Unissex')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='origem',
            field=models.CharField(choices=[('IMP', 'Importado'), ('NAC', 'Nacional')], max_length=3, verbose_name='Origem do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_aluguel_padrao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço do Aluguel'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Preço de Custo de Compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('COM', 'Comum'), ('DAM', 'Daminha'), ('DEB', 'Debutante'), ('FES', 'Festa'), ('MAD', 'Madrinha'), ('NVA', 'Noiva'), ('NVO', 'Noivo'), ('PAD', 'Padrinho')], max_length=3, verbose_name='Tipo do Produto'),
        ),
    ]
