# Generated by Django 6.0.5 on 2026-09-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_credito'),
        ('estoque', '0008_remove_tecido_composicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parâmetro do Sistema',
                'verbose_name_plural': 'Parâmetros do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField(auto_now_add=True)),
                ('data_retirada', models.DateField()),
                ('data_prova', models.DateField(editable=False)),
                ('data_devolucao_prevista', models.DateField(editable=False)),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('sinal_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto_ajuste', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto_indicacao_acumulado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('reservada', 'Reservada'), ('prova_agendada', 'Prova Agendada'), ('retirada', 'Retirada'), ('devolvida', 'Devolvida'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='reservada', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='clientes.cliente')),
                ('indicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes', to='locacoes.locacao', verbose_name='Indicado por (locação de quem indicou)')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
            },
        ),
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(blank=True, decimal_places=2, help_text='Se deixado em branco, é preenchido com o preço padrão do produto.', max_digits=10, null=True)),
                ('data_devolucao_real_item', models.DateField(blank=True, null=True)),
                ('retornou_lavanderia', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_locacao', to='estoque.produto')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='locacoes.locacao')),
            ],
            options={
                'verbose_name': 'Item da Locação',
                'verbose_name_plural': 'Itens da Locação',
            },
        ),
        migrations.AddIndex(
            model_name='locacao',
            index=models.Index(fields=['status', 'data_retirada'], name='locacoes_lo_status_f96a92_idx'),
        ),
        migrations.AddIndex(
            model_name='locacao',
            index=models.Index(fields=['status', 'data_devolucao_prevista'], name='locacoes_lo_status_84ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='itemlocacao',
            index=models.Index(fields=['produto'], name='locacoes_it_produto_37a133_idx'),
        ),
    ]
