# Generated by Django 6.0.5 on 2026-10-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locacao',
            old_name='desconto_ajuste',
            new_name='desconto',
        ),
    ]
