# Generated by Django 6.0.5 on 2026-06-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=1, max_length=7, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
