# Generated by Django 6.0.5 on 2026-06-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RG'),
        ),
    ]
