# Generated by Django 6.0.5 on 2026-06-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_email_alter_cliente_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Crédito'),
        ),
    ]
